### Invalid login, nonexistent email
POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "superduperwrong@nonexistent.com",
    "password": "wrong"
}


### Invalid login, invalid details
POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "dszone51@gmail.com",
    "password": "wrong"
}


### Successful login

POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "dszone51@gmail.com",
    "password": "dszone"
}

### Get info about self

GET http://localhost:8000/auth/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QvYXV0aC9sb2dpbiIsImlhdCI6MTY1OTUwODAzMywibmJmIjoxNjU5NTA4MDMzLCJqdGkiOiJkYzAzYWJhODhjOTlmZGU5NmQxYjI2ZmI2OTk5MmMiLCJleHAiOjE2NTk1MDg3MjMsInN1YiI6IjNlOTQ1MDhmLTU5M2EtNGIwYS05ODIyLTdjMDIyZmI3Mjg2MCJ9.FVRXiIJqVXKyPV17xTvmKwteKHAD38TEmZ0S03TpEmg



